const _ = require('lodash');

module.exports = {
    kclass: _.orderBy([
        'Leader',
        'Determined',
        'Mutant',
        'Cute',
        'Explorer',
        'Creative',
        'Sporty',
        'Arrogant',
        'Kind',
        'Sneaky',
        'Firey',
        'Warrior',
        'Adventurer',
        'Gross',
        'Hero',
        'Joker',
        'Prankster',
        'Intelligent',
        'Mythical',
        'Wizard',
        'Genius',
        'Doctor',
        'Witch',
        'Sophisticated',
        'Omnipotent',
        'Rare AF',
        'Devcon 5',
    ]),
    skills: _.orderBy([
        'Influential',
        'Cryptography Expert',
        'Hungry',
        'Lover',
        'Dancer',
        'Fluffy',
        'Writer',
        'Musician',
        'Liar',
        'Comedy',
        'Retired',
        'Technical',
        'Designer',
        'Fighter',
        'Fashionable',
        'Chubby',
        'Thief',
        'Magic',
        'Engineer',
        'Scavenger',
        'Communicator',
        'Entrepreneurial',
        'Analytical',
        'Tomfoolery',
        'Plumber',
        'Witty',
        'Flatulent',
        'Slimy',
        'Speedy',
        'Janitor',
        'Actor',
        'Gentleman',
        'Hodler',
        'Actress',
        'Psychic',
        'Collector',
        'Inquisitive',
        'Ambitious',
        'Brave',
        'Frugal',
        'Charming',
        'Frank',
        'Gregarious',
        'Philosophical',
        'Sailor',
        'Rascal',
        'UX Champion',
        'Spooky',
    ]),
};
